/*
 * Copyright (C) 2020 BlueKitchen GmbH
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 * notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 * notice, this list of conditions and the following disclaimer in the
 * documentation and/or other materials provided with the distribution.
 * 3. Neither the name of the copyright holders nor the names of
 * contributors may be used to endorse or promote products derived
 * from this software without specific prior written permission.
 * 4. Any redistribution, use, or modification is done solely for
 * personal benefit and not for any commercial purpose or for
 * monetary gain.
 *
 * THIS SOFTWARE IS PROVIDED BY BLUEKITCHEN GMBH AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL BLUEKITCHEN
 * GMBH OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF
 * THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 *
 * Please inquire about commercial licensing options at
 * contact@bluekitchen-gmbh.com
 *
 */

#define BTSTACK_FILE__ "hog_host_demo.c"

/*
 * hog_host_demo.c
 */

/* EXAMPLE_START(hog_host_demo): HID Host LE
 *
 * @text This example implements a minimal HID-over-GATT Host. It scans for LE HID devices, connects to it,
 * discovers the Characteristics relevant for the HID Service and enables Notifications on them.
 * It then dumps all Boot Keyboard and Mouse Input Reports
 */

#include <inttypes.h>
#include <stdio.h>
#include <btstack_tlv.h>

#include "btstack_config.h"
#include "btstack.h"

// hog_host_demo.gatt contains the declaration of the provided GATT Services + Characteristics
// hog_host_demo.h    contains the binary representation of gatt_browser.gatt
// it is generated by the build system by calling: $BTSTACK_ROOT/tool/compile_gatt.py hog_host_demo.gatt hog_host_demo.h
// it needs to be regenerated when the GATT Database declared in gatt_browser.gatt file is modified
#include "hog_host_demo.h"
// @@add
// =====>
#include "picow_bt_example_common.h"
#include "pico/cyw43_arch.h"
#include "Common.h"
// <=====

// @@add
// =====>
// Timeout constants
#define CONNECTION_TIMEOUT_MS 3000  // 3 seconds for connection attempt
#define SCAN_TIMEOUT_MS       5000  // 5 seconds for scanning
// <=====

// TAG to store remote device address and type in TLV
#define TLV_TAG_HOGD ((((uint32_t) 'H') << 24 ) | (((uint32_t) 'O') << 16) | (((uint32_t) 'G') << 8) | 'D')

typedef struct {
    bd_addr_t addr;
    bd_addr_type_t addr_type;
} le_device_addr_t;

static enum {
    W4_WORKING,
    W4_HID_DEVICE_FOUND,
    W4_CONNECTED,
    W4_ENCRYPTED,
    W4_HID_CLIENT_CONNECTED,
    READY,
    W4_TIMEOUT_THEN_SCAN,
    W4_TIMEOUT_THEN_RECONNECT,
} app_state;

static le_device_addr_t remote_device;
static hci_con_handle_t connection_handle;
static uint16_t hids_cid;
static hid_protocol_mode_t protocol_mode = HID_PROTOCOL_MODE_REPORT;

// SDP
static uint8_t hid_descriptor_storage[500];

// used to implement connection timeout and reconnect timer
static btstack_timer_source_t connection_timer;

// register for events from HCI/GAP and SM
static btstack_packet_callback_registration_t hci_event_callback_registration;
static btstack_packet_callback_registration_t sm_event_callback_registration;

// used to store remote device in TLV
static const btstack_tlv_t * btstack_tlv_singleton_impl;
static void * btstack_tlv_singleton_context;

// @@add
// =====>
extern volatile bool g_usb_reinit_request;
// <=====

// @@add
// =====>
void ble_host_main(void);
bool is_ble_app_state_ready(void);
const uint8_t* get_ble_hid_report_descriptor_data(void);
uint16_t get_ble_hid_report_descriptor_len(void);
// <=====

// @@add
// =====>
// Forward declarations
static void hog_start_scan(void);
static void hog_start_connect(void);
// <=====

// @@chg
// =====>
//static void hid_handle_input_report(uint8_t service_index, const uint8_t * report, uint16_t report_len){
static void hid_handle_input_report(uint8_t service_index, uint8_t report_id, const uint8_t * report, uint16_t report_len){
// <=====
    // check if HID Input Report
    
    // @@chg
    // =====>
    // Enqueue the raw report for the USB task.
    // The USB HID task manages transmission to the host.
    static ST_HID_RPT stHidRpt; // Change local variable to static to use static memory (data area) instead of stack, preventing stack overflow.

    stHidRpt.report_id  = report_id;
    stHidRpt.report_len = report_len;  
    // Prevent buffer overflow if the report is larger than the buffer
    if (stHidRpt.report_len > CMN_HID_RPT_DATA_SIZE) {
        stHidRpt.report_len = CMN_HID_RPT_DATA_SIZE;
    }
    memcpy(stHidRpt.report, report, stHidRpt.report_len);
    if (!CMN_Enqueue(CMN_QUE_KIND_HID_RPT, &stHidRpt)) {
        // Queue is full
    }
    return;
    // <=====    
}

/**
 * @section Test if advertisement contains HID UUID
 * @param packet
 * @param size
 * @returns true if it does
 */
static bool adv_event_contains_hid_service(const uint8_t * packet){
    const uint8_t * ad_data = gap_event_advertising_report_get_data(packet);
    uint8_t ad_len = gap_event_advertising_report_get_data_length(packet);
    return ad_data_contains_uuid16(ad_len, ad_data, ORG_BLUETOOTH_SERVICE_HUMAN_INTERFACE_DEVICE);
}

// @@add
// =====>
/**
 * Handle scan timeout: Stop scanning and try connecting to bonded device
 */
static void hog_scan_timeout(btstack_timer_source_t * ts){
    UNUSED(ts);
    if (app_state != W4_HID_DEVICE_FOUND) return;
    printf("Scan timeout. Switching to bonded connection attempt...\n");
    gap_stop_scan();
    hog_start_connect();
}
// <=====

/**
 * Start scanning
 */
static void hog_start_scan(void){
	// @@chg
	// =====>
    printf("Scanning for LE HID devices (Timeout %dms)...\n", SCAN_TIMEOUT_MS);
    app_state = W4_HID_DEVICE_FOUND;

    // Fix: Remove timer before adding to prevent assertion if scan is restarted during reconnection
    btstack_run_loop_remove_timer(&connection_timer);

    // Set timer to stop scanning and try connecting to bonded device
    btstack_run_loop_set_timer(&connection_timer, SCAN_TIMEOUT_MS);
    btstack_run_loop_set_timer_handler(&connection_timer, &hog_scan_timeout);
    btstack_run_loop_add_timer(&connection_timer);
	// <=====

    // Passive scanning, 100% (scan interval = scan window)
    gap_set_scan_parameters(0,48,48);
    gap_start_scan();
}

/**
 * Handle timeout for outgoing connection
 * @param ts
 */
static void hog_connection_timeout(btstack_timer_source_t * ts){
    UNUSED(ts);
    // @@chg
    // =====>
    printf("Connection timeout. Switching to scan...\n");
    // <=====
    gap_connect_cancel();
    hog_start_scan();
}


/**
 * Connect to remote device but set timer for timeout
 */
static void hog_connect(void) {
	// @@chg
	// =====>
    printf("Connecting to device %s (Timeout %dms)...\n", bd_addr_to_str(remote_device.addr), CONNECTION_TIMEOUT_MS);
    
    // Fix: Remove timer before adding. If a previous timer (like scan timeout) is still active, 
    // btstack_run_loop_add_timer would trigger an assertion failure.
    btstack_run_loop_remove_timer(&connection_timer);

    // Set timer for connection attempt
    btstack_run_loop_set_timer(&connection_timer, CONNECTION_TIMEOUT_MS);
    btstack_run_loop_set_timer_handler(&connection_timer, &hog_connection_timeout);
    btstack_run_loop_add_timer(&connection_timer);
    // <=====
    
    app_state = W4_CONNECTED;
    gap_connect(remote_device.addr, remote_device.addr_type);
}

/**
 * Start connecting after boot up: connect to last used device if possible, start scan otherwise
 */
static void hog_start_connect(void){
    // check if we have a bonded device
    btstack_tlv_get_instance(&btstack_tlv_singleton_impl, &btstack_tlv_singleton_context);
    if (btstack_tlv_singleton_impl){
        int len = btstack_tlv_singleton_impl->get_tag(btstack_tlv_singleton_context, TLV_TAG_HOGD, (uint8_t *) &remote_device, sizeof(remote_device));
        if (len == sizeof(remote_device)){
            // @@chg
            // =====>
            printf("Bonded device found, trying to connect...\n");
            // <=====
            hog_connect();
            return;
        }
    }
    // otherwise, scan for HID devices
    hog_start_scan();
}

/**
 * In case of error, disconnect and start scanning again
 */
static void handle_outgoing_connection_error(void){
    printf("Error occurred, disconnect and start over\n");
    gap_disconnect(connection_handle);
    hog_start_scan();
}

/**
 * Handle GATT Client Events dependent on current state
 *
 * @param packet_type
 * @param channel
 * @param packet
 * @param size
 */
static void handle_gatt_client_event(uint8_t packet_type, uint16_t channel, uint8_t *packet, uint16_t size) {
    UNUSED(packet_type);
    UNUSED(channel);
    UNUSED(size);

    uint8_t status;

    if (hci_event_packet_get_type(packet) != HCI_EVENT_GATTSERVICE_META){
        return;
    }
    
    switch (hci_event_gattservice_meta_get_subevent_code(packet)){
        case GATTSERVICE_SUBEVENT_HID_SERVICE_CONNECTED:
            status = gattservice_subevent_hid_service_connected_get_status(packet);
            switch (status){
                case ERROR_CODE_SUCCESS:
                    printf("HID service client connected, found %d services\n", 
                        gattservice_subevent_hid_service_connected_get_num_instances(packet));
        
                    // store device as bonded
                    if (btstack_tlv_singleton_impl){
                        btstack_tlv_singleton_impl->store_tag(btstack_tlv_singleton_context, TLV_TAG_HOGD, (const uint8_t *) &remote_device, sizeof(remote_device));
                    }
                    // done
                    printf("Ready - please start typing or mousing..\n");
                    app_state = READY;
                    // Re-initialize the USB device to make the USB host re-acquire the descriptor.
                    // This flag is referenced by USB task.
                    // @@add
                    // =====>
                    g_usb_reinit_request = true;
                    // <=====
                    break;
                default:
                    printf("HID service client connection failed, status 0x%02x.\n", status);
                    handle_outgoing_connection_error();
                    break;
            }
            break;

        case GATTSERVICE_SUBEVENT_HID_SERVICE_DISCONNECTED:
            printf("HID service client disconnected\n");
            // @@del
            // =====>
            //hog_start_connect();
            // <=====
            break;

        case GATTSERVICE_SUBEVENT_HID_REPORT:
            hid_handle_input_report(
                gattservice_subevent_hid_report_get_service_index(packet),
                // @@add
                // =====>
                gattservice_subevent_hid_report_get_report_id(packet), 
                // <=====
                gattservice_subevent_hid_report_get_report(packet), 
                gattservice_subevent_hid_report_get_report_len(packet));
            break;

        default:
            break;
    }
}

/* LISTING_START(packetHandler): Packet Handler */
static void packet_handler (uint8_t packet_type, uint16_t channel, uint8_t *packet, uint16_t size){
    /* LISTING_PAUSE */
    UNUSED(channel);
    UNUSED(size);
    uint8_t event;
    /* LISTING_RESUME */
    switch (packet_type) {
        case HCI_EVENT_PACKET:
            event = hci_event_packet_get_type(packet);
            switch (event) {
                case BTSTACK_EVENT_STATE:
                    if (btstack_event_state_get_state(packet) != HCI_STATE_WORKING) break;
                    btstack_assert(app_state == W4_WORKING);
                    
                    hog_start_connect();
                    break;
                // @@chg
                // =====>    
                case GAP_EVENT_ADVERTISING_REPORT:
                    if (app_state != W4_HID_DEVICE_FOUND) break;
                    if (adv_event_contains_hid_service(packet) == false) break;
                    
                    // Stop scan timeout timer and stop scan
                    btstack_run_loop_remove_timer(&connection_timer);
                    gap_stop_scan();

                    // store remote device address and type
                    gap_event_advertising_report_get_address(packet, remote_device.addr);
                    remote_device.addr_type = gap_event_advertising_report_get_address_type(packet);
                    
                    printf("Found HID device, connecting...\n");
                    hog_connect();
                    break;
                case HCI_EVENT_DISCONNECTION_COMPLETE:
                    connection_handle = HCI_CON_HANDLE_INVALID;
                    printf("\nDisconnected, starting over...\n");
                    
                    // Fix: Ensure timer is cleared upon disconnection before starting over
                    btstack_run_loop_remove_timer(&connection_timer);

                    // Wait a moment before restarting the loop
                    app_state = W4_WORKING;
                    hog_start_connect();
                // <=====    
                    break;
                case HCI_EVENT_META_GAP:
                    // wait for connection complete
                    if (hci_event_gap_meta_get_subevent_code(packet) != GAP_SUBEVENT_LE_CONNECTION_COMPLETE) break;
                    if (app_state != W4_CONNECTED) return;
                    btstack_run_loop_remove_timer(&connection_timer);
                    connection_handle = gap_subevent_le_connection_complete_get_connection_handle(packet);
                    // request security
                    app_state = W4_ENCRYPTED;
                    sm_request_pairing(connection_handle);
                    break;
                default:
                    break;
            }
            break;
        default:
            break;
    }
}
/* LISTING_END */

/* @section HCI packet handler
 *
 * @text The SM packet handler receives Security Manager Events required for pairing.
 * It also receives events generated during Identity Resolving
 * see Listing SMPacketHandler.
 */

/* LISTING_START(SMPacketHandler): Scanning and receiving advertisements */

static void sm_packet_handler(uint8_t packet_type, uint16_t channel, uint8_t *packet, uint16_t size){
    UNUSED(channel);
    UNUSED(size);

    if (packet_type != HCI_EVENT_PACKET) return;

    bool connect_to_service = false;

    switch (hci_event_packet_get_type(packet)) {
        case SM_EVENT_JUST_WORKS_REQUEST:
            printf("Just works requested\n");
            sm_just_works_confirm(sm_event_just_works_request_get_handle(packet));
            break;
        case SM_EVENT_NUMERIC_COMPARISON_REQUEST:
            printf("Confirming numeric comparison: %"PRIu32"\n", sm_event_numeric_comparison_request_get_passkey(packet));
            sm_numeric_comparison_confirm(sm_event_passkey_display_number_get_handle(packet));
            break;
        case SM_EVENT_PASSKEY_DISPLAY_NUMBER:
            printf("Display Passkey: %"PRIu32"\n", sm_event_passkey_display_number_get_passkey(packet));
            break;
        case SM_EVENT_PAIRING_COMPLETE:
            switch (sm_event_pairing_complete_get_status(packet)){
                case ERROR_CODE_SUCCESS:
                    printf("Pairing complete, success\n");
                    connect_to_service = true;
                    break;
                // @@chg
                // =====>    
                case ERROR_CODE_CONNECTION_TIMEOUT:
                    printf("Pairing failed, timeout\n");
                    handle_outgoing_connection_error();
                    break;
                default:
                    printf("Pairing failed, status 0x%02x\n", sm_event_pairing_complete_get_status(packet));
                    handle_outgoing_connection_error();
                    break;
                // <=====
            }
            break;
        case SM_EVENT_REENCRYPTION_COMPLETE:
            printf("Re-encryption complete, success\n");
            connect_to_service = true;
            break;
        default:
            break;
    }

    if (connect_to_service){
        // continue - query primary services
        printf("Search for HID service.\n");
        app_state = W4_HID_CLIENT_CONNECTED;
        hids_client_connect(connection_handle, handle_gatt_client_event, protocol_mode, &hids_cid);
    }
}
/* LISTING_END */

int btstack_main(int argc, const char * argv[]);
int btstack_main(int argc, const char * argv[]){

    (void)argc;
    (void)argv;

    /* LISTING_START(HogBootHostSetup): HID-over-GATT Host Setup */

    l2cap_init();

    // setup SM: Display only
    sm_init();
    sm_set_io_capabilities(IO_CAPABILITY_DISPLAY_ONLY);
    sm_set_authentication_requirements(SM_AUTHREQ_SECURE_CONNECTION | SM_AUTHREQ_BONDING);

    //
    gatt_client_init();

    // setup ATT server - only needed if LE Peripheral does ATT queries on its own, e.g. Android and iOS
    att_server_init(profile_data, NULL, NULL);

    hids_client_init(hid_descriptor_storage, sizeof(hid_descriptor_storage));

    // register for events from HCI
    hci_event_callback_registration.callback = &packet_handler;
    hci_add_event_handler(&hci_event_callback_registration);

    // register for events from Security Manager
    sm_event_callback_registration.callback = &sm_packet_handler;
    sm_add_event_handler(&sm_event_callback_registration);
    // @@del
    // =====>
    //sm_set_authentication_requirements( SM_AUTHREQ_BONDING);
    // <=====

    /* LISTING_END */

    // Disable stdout buffering
    setvbuf(stdin, NULL, _IONBF, 0);

    app_state = W4_WORKING;

    // Turn on the device
    hci_power_control(HCI_POWER_ON);
    return 0;
}

// @@add
// =====>
/**
 * @brief Main function for the BLE host task (runs on Core1).
 * 
 * @note This function initializes and runs the BTstack event loop.
 */
void ble_host_main(void)
{
    // Initialize BTstack for PicoW
    (void)picow_bt_example_init();
    // Set up and start the main BTstack task
    picow_bt_example_main();
    // Enter the BTstack run loop
    btstack_run_loop_execute();
}
// <=====

/**
 * @brief Check if the BLE application state is READY.
 * 
 * @return true if the application state is READY, false otherwise.
 */
bool is_ble_app_state_ready(void)
{
    return (READY == app_state) ? true : false;
}

/**
 * @brief Get the pointer to the HID Report Descriptor received via BLE.
 * 
 * @return Pointer to the HID Report Descriptor data.
 */
const uint8_t* get_ble_hid_report_descriptor_data(void)
{
    return hids_client_descriptor_storage_get_descriptor_data(hids_cid, 0);
}

/**
 * @brief Get the length of the HID Report Descriptor received via BLE.
 * 
 * @return Length of the HID Report Descriptor.
 */
uint16_t get_ble_hid_report_descriptor_len(void)
{
    return hids_client_descriptor_storage_get_descriptor_len(hids_cid, 0);
}

/* EXAMPLE_END */
